[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "8m6WUJiMAy15kEPnJQEQmvzKBEKk3Hpvwj22Nuxs42eL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/tituscoleman/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
